# -*- coding: utf-8 -*-
"""Remesas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PLPUw1Ys95WNx1yTCmsrxOQ0lUUAJ1Ts
"""

# app.py
# Streamlit app: ¿Es buen momento para enviar remesas de EE.UU. a México?
# Usa yfinance (USD/MXN) + FinBERT (sentimiento noticias financieras)

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# =============================
# Configuración inicial
# =============================
st.set_page_config(page_title="Remesas EE.UU. → México", layout="centered")

st.title("💸 ¿Conviene enviar remesa hoy?")
st.caption("Tipo de cambio USD/MXN + sentimiento financiero (FinBERT)")

# =============================
# Cargar FinBERT
# =============================
@st.cache_resource

def load_finbert():
    tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
    model = AutoModelForSequenceClassification.from_pretrained("ProsusAI/finbert")
    return tokenizer, model

tokenizer, model = load_finbert()
labels = ["negative", "neutral", "positive"]

# =============================
# Tipo de cambio USD/MXN
# =============================
@st.cache_data(ttl=3600)

def get_fx_data(period="6mo"):
    ticker = yf.Ticker("MXN=X")
    df = ticker.history(period=period)
    return df

fx = get_fx_data()

current_fx = fx['Close'].iloc[-1]
mean_fx = fx['Close'].mean()

# =============================
# Noticias desde yfinance (ticker.news)
# =============================

@st.cache_data(ttl=3600)

def get_news():
    ticker = yf.Ticker("MXN=X")
    news = ticker.news
    if news is None:
        return []
    return news[:5]  # últimas 5 noticias

news_items = get_news()

st.subheader("📰 Noticias financieras recientes (USD/MXN)")

if len(news_items) == 0:
    st.warning("No se pudieron obtener noticias. Usando texto neutro.")
    news_text = "The foreign exchange market remains stable."
else:
    news_texts = []
    for n in news_items:
        title = n.get('title', '')
        summary = n.get('summary', '')
        st.write(f"**• {title}**")
        news_texts.append(title + ". " + summary)
    news_text = " ".join(news_texts)

# =============================
# Análisis de sentimiento con FinBERT
# =============================

def finbert_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
    sentiment = labels[torch.argmax(probs)]
    score = probs[labels.index("positive")] - probs[labels.index("negative")]
    return sentiment, score.item()

sentiment, sentiment_score = finbert_sentiment(news_text)

# =============================
# Heurística de decisión
# =============================
# Regla simple:
# - Conviene enviar si USD/MXN está arriba de su promedio reciente
# - Y el sentimiento no es claramente negativo

if (current_fx > mean_fx) and (sentiment != "negative"):
    decision = "✅ PROPICIO enviar remesa"
    color = "green"
elif (current_fx > mean_fx) and (sentiment == "negative"):
    decision = "⚠️ Tipo de cambio bueno, pero riesgo macro"
    color = "orange"
else:
    decision = "❌ NO es buen momento para enviar"
    color = "red"

# =============================
# Resultados
# =============================
st.subheader("📊 Resultados")

col1, col2 = st.columns(2)

with col1:
    st.metric("USD/MXN actual", f"{current_fx:.2f}")
    st.metric("Promedio 6 meses", f"{mean_fx:.2f}")

with col2:
    st.write("**Sentimiento (FinBERT):**", sentiment)
    st.write("**Score sentimiento:**", round(sentiment_score, 3))

st.markdown(f"### :{color}[{decision}]")

# =============================
# Gráfica
# =============================
st.subheader("📈 Evolución USD/MXN")
st.line_chart(fx['Close'])

# =============================
# Disclaimer
# =============================
st.caption("⚠️ Herramienta educativa. No constituye recomendación financiera. Heurística simplificada.")